"""
ConversaETL — Conceptual Pipeline Demo: Basic Temporal Aggregation
==================================================================

This script illustrates how ConversaETL processes a natural-language ETL request
through its five stages: planning, critique, semantic resolution, compilation,
and contract validation.

This is a SIMPLIFIED EDUCATIONAL ILLUSTRATION using synthetic data.
It demonstrates the interaction model and typed intermediate representation.
The production system uses a full LLM-assisted planner and deterministic
compiler stack — neither is exposed here.

Requirements: pandas (pip install pandas)
"""

from __future__ import annotations

import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import pandas as pd

DATA_DIR = Path(__file__).parent.parent / "sample_data"


# ---------------------------------------------------------------------------
# Typed Intermediate Representation
# ---------------------------------------------------------------------------
# In ConversaETL, the LLM-assisted planner produces a typed plan like this.
# The plan is inspectable, normalizable, and critique-able — unlike raw code.

@dataclass
class TypedETLPlan:
    """
    Typed intermediate representation produced by the ConversaETL planner.

    In the production system, this is generated by an LLM-assisted intent
    planner from the natural-language request and a profiled schema context.
    """
    natural_language: str
    task_family: str          # e.g. "date_wrangling", "aggregate", "cleaning"
    metric: str               # semantic metric reference (not yet a column name)
    group_by: list[str]
    period: str | None = None  # e.g. "2024-Q1", "2024-Q2"
    operator: str = "sum"
    filters: dict[str, Any] = field(default_factory=dict)

    def __str__(self) -> str:
        lines = [
            "TypedETLPlan {",
            f"  query      : '{self.natural_language}'",
            f"  task_family: {self.task_family}",
            f"  metric     : {self.metric}",
            f"  group_by   : {self.group_by}",
            f"  period     : {self.period}",
            f"  operator   : {self.operator}",
            f"  filters    : {self.filters}",
            "}",
        ]
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Stage 2 — Plan Critique (simplified illustration)
# ---------------------------------------------------------------------------

class PlanCritic:
    """
    Validates the typed plan before semantic resolution.

    In the production system, the plan critic checks structural constraints,
    operator-family consistency, and task-family invariants.
    """
    SUPPORTED_FAMILIES = {"aggregate", "date_wrangling", "cleaning", "grounded_insight"}

    def validate(self, plan: TypedETLPlan) -> tuple[bool, str]:
        if plan.task_family not in self.SUPPORTED_FAMILIES:
            return False, f"Unsupported task family: {plan.task_family}"
        if not plan.metric:
            return False, "Plan missing required metric field"
        if not plan.group_by:
            return False, "Plan missing group_by — required for aggregation"
        return True, "OK"


# ---------------------------------------------------------------------------
# Stage 3 — Semantic Resolution (simplified illustration)
# ---------------------------------------------------------------------------

SCHEMA_ALIASES: dict[str, str] = {
    "revenue":  "amount",
    "sales":    "amount",
    "spend":    "amount",
    "turnover": "amount",
    "qty":      "quantity",
    "units":    "quantity",
    "status":   "status",
    "region":   "region",
    "category": "category",
}

def resolve_metric(metric_ref: str, available_columns: list[str]) -> str | None:
    """
    Binds a semantic metric reference to an actual schema column.

    In the production system, the semantic metric resolver uses schema profiling,
    role inference, and cross-table candidate scoring.
    """
    candidate = SCHEMA_ALIASES.get(metric_ref.lower(), metric_ref.lower())
    if candidate in available_columns:
        return candidate
    return None


# ---------------------------------------------------------------------------
# Stage 4 — Deterministic Compilation and Execution (simplified illustration)
# ---------------------------------------------------------------------------

QUARTER_MONTHS: dict[str, list[int]] = {
    "Q1": [1, 2, 3],
    "Q2": [4, 5, 6],
    "Q3": [7, 8, 9],
    "Q4": [10, 11, 12],
}

def compile_and_execute(
    plan: TypedETLPlan,
    df: pd.DataFrame,
    resolved_metric: str,
) -> pd.DataFrame:
    """
    Deterministic compilation and execution.

    In the production system, a family of bounded compilers handles this stage.
    No LLM-generated code is executed. The transformation is fully determined
    by the typed plan and the schema.
    """
    result = df.copy()

    # Apply period filter
    if plan.period:
        year_str, quarter_str = plan.period.split("-")
        months = QUARTER_MONTHS.get(quarter_str, [])
        result = result[
            (result["order_date"].dt.year == int(year_str))
            & (result["order_date"].dt.month.isin(months))
        ]

    # Apply filters
    for col, val in plan.filters.items():
        if col in result.columns:
            result = result[result[col] == val]

    # Resolve group_by columns (semantic aliases)
    resolved_group = []
    for g in plan.group_by:
        resolved = resolve_metric(g, list(result.columns))
        resolved_group.append(resolved if resolved else g)

    # Aggregate
    result = (
        result.groupby(resolved_group)[resolved_metric]
        .agg(plan.operator)
        .reset_index()
        .sort_values(resolved_metric, ascending=False)
        .rename(columns={resolved_metric: f"total_{resolved_metric}"})
    )
    return result


# ---------------------------------------------------------------------------
# Stage 5 — Contract Validation (simplified illustration)
# ---------------------------------------------------------------------------

@dataclass
class OutputContract:
    required_columns: list[str]
    min_rows: int = 1

def validate_contract(df: pd.DataFrame, contract: OutputContract) -> tuple[bool, str]:
    """
    Validates the output against the contract specification.

    In the production system, contracts enforce schema shape, null bounds,
    and evidence requirements. Failed contracts produce structured rejection records.
    """
    missing = [c for c in contract.required_columns if c not in df.columns]
    if missing:
        return False, f"CONTRACT FAIL — missing columns: {missing}"
    if len(df) < contract.min_rows:
        return False, f"CONTRACT FAIL — result has {len(df)} rows, minimum {contract.min_rows}"
    return True, "CONTRACT PASS"


# ---------------------------------------------------------------------------
# Main Pipeline Illustration
# ---------------------------------------------------------------------------

def run_demo() -> None:
    print("=" * 65)
    print("  ConversaETL — Conceptual Pipeline Illustration")
    print("  Example: Temporal Aggregation with Period Filter")
    print("=" * 65)

    # Load synthetic data
    orders = pd.read_csv(DATA_DIR / "orders.csv", parse_dates=["order_date"])
    products = pd.read_csv(DATA_DIR / "products.csv")
    merged = orders.merge(
        products[["product_id", "category"]], on="product_id", how="left"
    )

    # ── STAGE 1: Natural Language Input ──────────────────────────────────
    nl_query = "What are total sales by product category in Q2 2024, ranked by revenue?"
    print(f"\n[STAGE 1 — INPUT]\n  Query: \"{nl_query}\"")

    # ── STAGE 1: Typed Plan (in production: LLM-assisted planner output) ─
    plan = TypedETLPlan(
        natural_language=nl_query,
        task_family="aggregate",
        metric="revenue",       # semantic reference, not yet a column name
        group_by=["category"],
        period="2024-Q2",
        operator="sum",
    )
    print(f"\n[STAGE 1 — TYPED PLAN]\n{plan}")

    # ── STAGE 2: Plan Critique ────────────────────────────────────────────
    critic = PlanCritic()
    valid, reason = critic.validate(plan)
    print(f"\n[STAGE 2 — PLAN CRITIQUE]  {reason}")
    if not valid:
        print("  Pipeline halted — plan rejected.")
        sys.exit(1)

    # ── STAGE 3: Semantic Resolution ──────────────────────────────────────
    resolved_metric = resolve_metric(plan.metric, list(merged.columns))
    if resolved_metric is None:
        print(f"\n[STAGE 3 — SEMANTIC RESOLUTION]  FAIL — '{plan.metric}' not bound")
        sys.exit(1)
    print(f"\n[STAGE 3 — SEMANTIC RESOLUTION]  '{plan.metric}' → '{resolved_metric}'")

    # ── STAGE 4: Deterministic Compilation and Execution ─────────────────
    result = compile_and_execute(plan, merged, resolved_metric)
    print(f"\n[STAGE 4 — COMPILATION]  {len(result)} rows produced")

    # ── STAGE 5: Contract Validation ──────────────────────────────────────
    contract = OutputContract(
        required_columns=["category", "total_amount"],
        min_rows=1,
    )
    passed, contract_msg = validate_contract(result, contract)
    print(f"\n[STAGE 5 — VALIDATION]  {contract_msg}")
    if not passed:
        print("  Result rejected — not returned.")
        sys.exit(1)

    # ── Output ────────────────────────────────────────────────────────────
    print("\n[OUTPUT — Validated ETL Result]")
    print("-" * 45)
    print(result.to_string(index=False))
    print("-" * 45)
    print(
        f"\n[AUDIT TRACE]\n"
        f"  task_family : {plan.task_family}\n"
        f"  metric      : {plan.metric} → {resolved_metric}\n"
        f"  period      : {plan.period}\n"
        f"  operator    : {plan.operator}\n"
        f"  rows_out    : {len(result)}\n"
        f"  contract    : PASS\n"
    )
    print("=" * 65)


if __name__ == "__main__":
    run_demo()
